# Apple Financial Supply Chain Ripple Analysis

## Introduction  
Apple is one of the largest smartphone manufacturers. However, in 2018, the company faced a crisis that not only impacted its own market but also caused a ripple effect, affecting upstream companies like Qualcomm and Corning, which supply goods to Apple. Additionally, an ETF called XLK was used to assess whether the impact was limited to the supply chain or if it indicated a broader market decline.

Data was extracted using Yahoo Finance from 2017 to 2020, initially containing 3,176 rows.

### Key Questions Addressed in This Analysis
- To what extent did changes in AAPL correlate with changes in its upstream suppliers?
- Did the shifts in upstream companies occur before or after the changes in AAPL?
- How significant was the impact on the upstream companies?
- When did the decline start to recover?
- What was the market situation before and after the decline?

## Objectives
- Analyze the 2018 Apple crisis
- Load the data using a database or directly from a CSV file
- Convert the data into an analyzable format
- Detect patterns and visualize the data
- Answer the questions asked

# Importing Data

__Note__ Please note that the database is stored only on the local computer. Therefore, we implemented exception handling to allow data to be loaded either from the database or from CSV files. Since the dataset is not large, we can directly load it into Pandas data frames, enabling anyone to run this notebook.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [2]:
import getpass
try:
    db_password = getpass.getpass("Enter PostgreSQL password: ")
    engine = create_engine(
        f"postgresql+psycopg2://postgres:{db_password}@localhost:5432/apple_crises_db"
    )
    market_df = pd.read_sql(
        "SELECT * FROM market_data ORDER BY ticker, trade_date", 
        engine
    )
    assets_df = pd.read_sql("SELECT * FROM assets", engine)
    engine.dispose()
    print("Loaded from PostgreSQL database")
    
except Exception as e:
    market_df = pd.read_csv(
        "../data/raw/market_data.csv", 
        parse_dates=["trade_date"]
    )
    assets_df = pd.read_csv("../data/raw/assets.csv")
    print(f"PostgreSQL database is unavailable — loaded from CSV files.")
    print(f"THE HIDDEN ERROR IS: {e}")

Enter PostgreSQL password:  ········

Loaded from PostgreSQL database

In [3]:
display(market_df.head(4))

,trade_date,ticker,open,high,low,close,adj_close,volume
0,2017-01-03,AAPL,28.950001,29.082500,28.690001,29.037500,26.698212,115127600
1,2017-01-04,AAPL,28.962500,29.127501,28.937500,29.004999,26.668327,84472400
2,2017-01-05,AAPL,28.980000,29.215000,28.952499,29.152500,26.803949,88774400
3,2017-01-06,AAPL,29.195000,29.540001,29.117500,29.477501,27.102762,127007600

# Cleaning / Information of the Data

## Modifying the Data to Achieve the Desired Format

- We reshaped the raw long-format data into two wide-format matrices (Price and Volume) indexed by date, isolating the metric required for time-series calculations.
- We used adjusted close prices instead of simple close prices, as factors like stock splits and dividend payouts can lead to significant drops or spikes in the data.

In [4]:
# 1. Extract only the Price Matrix for return calculations
price_df = market_df.pivot(index='trade_date', columns='ticker', values='adj_close')

# 2. Extract only the Volume Matrix for later context
volume_df = market_df.pivot(index='trade_date', columns='ticker', values='volume')

## Information

In [8]:
# Shape of data frames
print(f"Price Matrix Shape: {price_df.shape}")
print(f"Volume Matrix Shape: {volume_df.shape}")
# Null values of the data frame
display(price_df.isnull().sum())
display(volume_df.isnull().sum())

Price Matrix Shape: (794, 4)
Volume Matrix Shape: (794, 4)

ticker
AAPL    0
GLW     0
QCOM    0
XLK     0
dtype: int64

ticker
AAPL    0
GLW     0
QCOM    0
XLK     0
dtype: int64

### Re-indexed and filled in the missing values as a precaution for potential future data additions.

In [6]:
price_df.index = pd.to_datetime(price_df.index)
price_df = price_df.ffill().dropna()
volume_df.index = pd.to_datetime(volume_df.index)
volume_df = volume_df.ffill().dropna()

### Conversion of daily Prices into daily Returns

- Daily returns normalize different price scales, allowing day-to-day volatility and correlation to be compared directly
- Immediately exclude the Day 1 mathematical NaN, as its return cannot be calculated due to the absence of a previous value.

In [7]:
# Calculate daily returns 
daily_returns = price_df.pct_change().dropna()
display(daily_returns.head())

ticker          AAPL       GLW      QCOM       XLK
trade_date
2017-01-04 -0.001119  0.006585  0.001070  0.003484
2017-01-05  0.005086 -0.006133  0.001222  0.001634
2017-01-06  0.011148  0.008638 -0.000305  0.007341
2017-01-09  0.009160 -0.002039  0.001831 -0.000202
2017-01-10  0.001008  0.000818 -0.000305  0.000202